/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as ConectarRouteImport } from './routes/conectar'
import { Route as CreatorDnaRouteImport } from './routes/creator-dna'
import { Route as LaboratorioRouteImport } from './routes/laboratorio'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as ProximoVideoRouteImport } from './routes/proximo-video'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as TendenciasRouteImport } from './routes/tendencias'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectarRoute = ConectarRouteImport.update({
  id: '/conectar',
  path: '/conectar',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorDnaRoute = CreatorDnaRouteImport.update({
  id: '/creator-dna',
  path: '/creator-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratorioRoute = LaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximoVideoRoute = ProximoVideoRouteImport.update({
  id: '/proximo-video',
  path: '/proximo-video',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const TendenciasRoute = TendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/conectar': typeof ConectarRoute
  '/creator-dna': typeof CreatorDnaRoute
  '/laboratorio': typeof LaboratorioRoute
  '/oportunidades': typeof OportunidadesRoute
  '/proximo-video': typeof ProximoVideoRoute
  '/seguranca': typeof SegurancaRoute
  '/tendencias': typeof TendenciasRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/conectar': typeof ConectarRoute
  '/creator-dna': typeof CreatorDnaRoute
  '/laboratorio': typeof LaboratorioRoute
  '/oportunidades': typeof OportunidadesRoute
  '/proximo-video': typeof ProximoVideoRoute
  '/seguranca': typeof SegurancaRoute
  '/tendencias': typeof TendenciasRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/conectar': typeof ConectarRoute
  '/creator-dna': typeof CreatorDnaRoute
  '/laboratorio': typeof LaboratorioRoute
  '/oportunidades': typeof OportunidadesRoute
  '/proximo-video': typeof ProximoVideoRoute
  '/seguranca': typeof SegurancaRoute
  '/tendencias': typeof TendenciasRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/conectar'
    | '/creator-dna'
    | '/laboratorio'
    | '/oportunidades'
    | '/proximo-video'
    | '/seguranca'
    | '/tendencias'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/conectar'
    | '/creator-dna'
    | '/laboratorio'
    | '/oportunidades'
    | '/proximo-video'
    | '/seguranca'
    | '/tendencias'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/conectar'
    | '/creator-dna'
    | '/laboratorio'
    | '/oportunidades'
    | '/proximo-video'
    | '/seguranca'
    | '/tendencias'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  ConectarRoute: typeof ConectarRoute
  CreatorDnaRoute: typeof CreatorDnaRoute
  LaboratorioRoute: typeof LaboratorioRoute
  OportunidadesRoute: typeof OportunidadesRoute
  ProximoVideoRoute: typeof ProximoVideoRoute
  SegurancaRoute: typeof SegurancaRoute
  TendenciasRoute: typeof TendenciasRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectar': {
      id: '/conectar'
      path: '/conectar'
      fullPath: '/conectar'
      preLoaderRoute: typeof ConectarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-dna': {
      id: '/creator-dna'
      path: '/creator-dna'
      fullPath: '/creator-dna'
      preLoaderRoute: typeof CreatorDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratorio': {
      id: '/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof LaboratorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximo-video': {
      id: '/proximo-video'
      path: '/proximo-video'
      fullPath: '/proximo-video'
      preLoaderRoute: typeof ProximoVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendencias': {
      id: '/tendencias'
      path: '/tendencias'
      fullPath: '/tendencias'
      preLoaderRoute: typeof TendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  ConectarRoute: ConectarRoute,
  CreatorDnaRoute: CreatorDnaRoute,
  LaboratorioRoute: LaboratorioRoute,
  OportunidadesRoute: OportunidadesRoute,
  ProximoVideoRoute: ProximoVideoRoute,
  SegurancaRoute: SegurancaRoute,
  TendenciasRoute: TendenciasRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
