/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as ProximoVideoRouteImport } from './routes/proximo-video'
import { Route as TendenciasRouteImport } from './routes/tendencias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximoVideoRoute = ProximoVideoRouteImport.update({
  id: '/proximo-video',
  path: '/proximo-video',
  getParentRoute: () => rootRouteImport,
} as any)
const TendenciasRoute = TendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oportunidades': typeof OportunidadesRoute
  '/proximo-video': typeof ProximoVideoRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oportunidades': typeof OportunidadesRoute
  '/proximo-video': typeof ProximoVideoRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oportunidades': typeof OportunidadesRoute
  '/proximo-video': typeof ProximoVideoRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oportunidades' | '/proximo-video' | '/tendencias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oportunidades' | '/proximo-video' | '/tendencias'
  id: '__root__' | '/' | '/oportunidades' | '/proximo-video' | '/tendencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OportunidadesRoute: typeof OportunidadesRoute
  ProximoVideoRoute: typeof ProximoVideoRoute
  TendenciasRoute: typeof TendenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximo-video': {
      id: '/proximo-video'
      path: '/proximo-video'
      fullPath: '/proximo-video'
      preLoaderRoute: typeof ProximoVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendencias': {
      id: '/tendencias'
      path: '/tendencias'
      fullPath: '/tendencias'
      preLoaderRoute: typeof TendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OportunidadesRoute: OportunidadesRoute,
  ProximoVideoRoute: ProximoVideoRoute,
  TendenciasRoute: TendenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
